#Referência
#https://github.com/wweber993/labsoc

version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  thehive:
    image: strangebee/thehive:5
    depends_on:
      - elasticsearch
    ports:
      - "9000:9000"
    environment:
      - "THEHIVE_elasticsearch.hosts=[\"http://elasticsearch:9200\"]"
    volumes:
      - thehive-data:/opt/thehive/data

volumes:
  esdata:
  thehive-data:
