apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  creationTimestamp: '2025-06-11T15:17:40Z'
  generation: 3
  managedFields:
    - apiVersion: logging.banzaicloud.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:active: {}
      manager: manager
      operation: Update
      subresource: status
      time: '2025-06-11T15:17:40Z'
    - apiVersion: logging.banzaicloud.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:globalOutputRefs: {}
      manager: rancher
      operation: Update
      time: '2025-06-11T15:28:59Z'
  name: all-logs
  namespace: cattle-logging-system
  resourceVersion: '587204'
  uid: 2d13edd3-859a-4c12-bcaa-5ed7754e076f
spec:
  globalOutputRefs:
    - wazuh-remote-syslog
status:
  active: true